sudo: false
group: travis_latest
language: vim

cache:
  apt: true
  yarn: true
  ccache: true

before_install:
  - git clone https://github.com/junegunn/vader.vim.git tests/vader.vim

jobs:
  include:
  - env: ENV="Vim8"
    install:
      - git clone https://github.com/vim/vim /tmp/vim
      - cd /tmp/vim
      - sudo apt-get install -y gettext libncurses5-dev libacl1-dev libgpm-dev
      - ./configure --with-features=huge --enable-fail-if-missing --enable-pythoninterp --prefix=$HOME/bin/vim
      - make && make install

    before_script:
      - cd $HOME/build/heavenshell/vim-jsdoc
      - make install

    script:
      - cd $HOME/build/heavenshell/vim-jsdoc/tests
      - VIM_EXE=$HOME/bin/vim/bin/vim ./run.sh
      
  - env: ENV="Neovim"
    install:
      - mkdir -p ~/tmp/nvim/bin
      - curl -L https://github.com/neovim/neovim/releases/download/v0.4.3/nvim.appimage -o ~/tmp/nvim/bin/nvim
      - chmod u+x ~/tmp/nvim/bin/nvim

    script:
      - cd $HOME/build/heavenshell/vim-jsdoc/tests
      - VIM_EXE=$HOME/tmp/nvim/bin/nvim ./run.sh
