name: build

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        name: [neovim-v05-x64]
        include:
          - name: neovim-v05-x64
            os: ubuntu-latest
            neovim_version: v0.8.1
    runs-on: ${{matrix.os}}
    steps:
      - name: Initialization
        run: |
          sudo apt-get update
          # libfuse2 and LD_PRELOAD are needed for appimage.
          sudo apt-get -y install libfuse2
          echo "LD_PRELOAD=/lib/x86_64-linux-gnu/libgmodule-2.0.so" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Download vim
        shell: bash
        run: |
          mkdir -p ~/nvim/bin
          curl -L https://github.com/neovim/neovim/releases/download/${{matrix.neovim_version}}/nvim.appimage -o ~/nvim/bin/nvim
          chmod u+x ~/nvim/bin/nvim
      - name: Download test runner
        shell: bash
        run: |
          git clone --depth 1 --single-branch https://github.com/junegunn/vader.vim.git ./tests/vader.vim
          make install

      - name: Run tests
        shell: bash
        run: |
          export PATH=~/nvim/bin:$PATH
          cd ./tests
          nvim -u vimrc -c 'Vader! *.vader'
